//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunevRestoraunt.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Dish = new HashSet<Dish>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int WaiterId { get; set; }
        public System.DateTime DateTimeOrdered { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> TableId { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Table Table { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dish> Dish { get; set; }
    }
}
